
title: Ayesha Saeed
bio: RF Antenna Design Engineer 
logo: 

# if it's an external image, update below for true
# better with square images
external-image: true
picture: assets/images/Ayesha.jpeg
remote_theme: https://sergiokopplin.github.io/indigo/
